version: '3.1'

services:
  golang:
    image: golang:1.18-stretch
    container_name: golang-demo
    ports:
      - 8000:8000
    volumes:
      - ./../../../src:/opt/app/src
      - ./../../../testdata:/opt/app/testdata
      - ./../../../lib/1.0.0/go-18:/opt/app/src/lib
      - ./../../../mock:/tmp/mock
    working_dir: /opt/app/src
    command: go run main.go jsight.go mock.go
